name: desafio_marvel
description: "App para buscar personagens da Marvel - Desafio Serasa Experian"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_modular: ^6.3.4
  dio: ^5.1.1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5 
  flutter_dotenv: ^6.0.0
  crypto: ^3.0.3
  flutter_native_splash: ^2.4.6
  shimmer_animation: ^2.2.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  flutter_lints: ^5.0.0
  

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/

flutter_native_splash:
  color: "#000000"
  image: assets/images/splash.png
  android: true
  ios: true
  ios_content_mode: scaleAspectFit

  android_gravity: center
  android_12:
    color: "#000000"
    image: assets/images/splash.png
